name: CI for Pushes

on:
  push:
    branches:
      - test2
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust the Node.js version as needed

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Install frontend dependencies and build
        run: |
          cd frontend
          npm install
          npm run build
